# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoAnnotator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(404, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 4, 4, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 2)
        self.lineEditNewName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNewName.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEditNewName.setObjectName("lineEditNewName")
        self.gridLayout_2.addWidget(self.lineEditNewName, 1, 2, 1, 1)
        self.pushButtonChooseSource = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChooseSource.sizePolicy().hasHeightForWidth())
        self.pushButtonChooseSource.setSizePolicy(sizePolicy)
        self.pushButtonChooseSource.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButtonChooseSource.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButtonChooseSource.setFont(font)
        self.pushButtonChooseSource.setStyleSheet("QPushButton{\n"
"    color: #334443;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 #84fab0, stop:1 #8fd3f4);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.pushButtonChooseSource.setObjectName("pushButtonChooseSource")
        self.gridLayout_2.addWidget(self.pushButtonChooseSource, 0, 0, 1, 2)
        self.lineEditSource = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSource.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEditSource.setText("")
        self.lineEditSource.setObjectName("lineEditSource")
        self.gridLayout_2.addWidget(self.lineEditSource, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 4, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem6, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_me = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_me.setObjectName("checkBox_me")
        self.gridLayout.addWidget(self.checkBox_me, 0, 0, 1, 2)
        self.checkBox_bird = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_bird.setObjectName("checkBox_bird")
        self.gridLayout.addWidget(self.checkBox_bird, 1, 0, 1, 1)
        self.checkBox_food = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_food.setObjectName("checkBox_food")
        self.gridLayout.addWidget(self.checkBox_food, 2, 0, 1, 2)
        self.checkBox_sky = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_sky.setObjectName("checkBox_sky")
        self.gridLayout.addWidget(self.checkBox_sky, 2, 2, 1, 2)
        self.checkBox_field = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_field.setObjectName("checkBox_field")
        self.gridLayout.addWidget(self.checkBox_field, 2, 4, 1, 1)
        self.checkBox_buildingin = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_buildingin.setObjectName("checkBox_buildingin")
        self.gridLayout.addWidget(self.checkBox_buildingin, 3, 0, 1, 2)
        self.checkBox_buildingout = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_buildingout.setObjectName("checkBox_buildingout")
        self.gridLayout.addWidget(self.checkBox_buildingout, 3, 2, 1, 3)
        self.checkBox_specialevent = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_specialevent.setObjectName("checkBox_specialevent")
        self.gridLayout.addWidget(self.checkBox_specialevent, 4, 0, 1, 2)
        self.checkBox_specialspot = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_specialspot.setObjectName("checkBox_specialspot")
        self.gridLayout.addWidget(self.checkBox_specialspot, 4, 2, 1, 3)
        self.checkBox_walkanimal = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_walkanimal.setObjectName("checkBox_walkanimal")
        self.gridLayout.addWidget(self.checkBox_walkanimal, 1, 2, 1, 2)
        self.checkBox_local = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_local.setObjectName("checkBox_local")
        self.gridLayout.addWidget(self.checkBox_local, 0, 4, 1, 1)
        self.checkBox_pal = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_pal.setObjectName("checkBox_pal")
        self.gridLayout.addWidget(self.checkBox_pal, 0, 2, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 4, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonPrevious = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPrevious.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButtonPrevious.setFont(font)
        self.pushButtonPrevious.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: #34656d;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.pushButtonPrevious.setObjectName("pushButtonPrevious")
        self.horizontalLayout.addWidget(self.pushButtonPrevious)
        self.pushButtonPlay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPlay.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButtonPlay.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButtonPlay.setFont(font)
        self.pushButtonPlay.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: #ff8474;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.pushButtonPlay.setText("")
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.horizontalLayout.addWidget(self.pushButtonPlay)
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButtonNext.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: #34656d;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.horizontalLayout.addWidget(self.pushButtonNext)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem8, 3, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 3)
        spacerItem9 = QtWidgets.QSpacerItem(404, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 2, 0, 1, 1)
        self.pushButtonSaveLabels = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSaveLabels.sizePolicy().hasHeightForWidth())
        self.pushButtonSaveLabels.setSizePolicy(sizePolicy)
        self.pushButtonSaveLabels.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButtonSaveLabels.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButtonSaveLabels.setFont(font)
        self.pushButtonSaveLabels.setStyleSheet("QPushButton{\n"
"    color: #334443;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 #84fab0, stop:1 #8fd3f4);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.pushButtonSaveLabels.setObjectName("pushButtonSaveLabels")
        self.gridLayout_4.addWidget(self.pushButtonSaveLabels, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Video Annotator"))
        self.label.setText(_translate("MainWindow", "New name:"))
        self.pushButtonChooseSource.setText(_translate("MainWindow", "Choose source"))
        self.checkBox_me.setText(_translate("MainWindow", "me"))
        self.checkBox_bird.setText(_translate("MainWindow", "bird"))
        self.checkBox_food.setText(_translate("MainWindow", "food"))
        self.checkBox_sky.setText(_translate("MainWindow", "sky"))
        self.checkBox_field.setText(_translate("MainWindow", "field"))
        self.checkBox_buildingin.setText(_translate("MainWindow", "buildingin"))
        self.checkBox_buildingout.setText(_translate("MainWindow", "buildingout"))
        self.checkBox_specialevent.setText(_translate("MainWindow", "specialevent"))
        self.checkBox_specialspot.setText(_translate("MainWindow", "specialspot"))
        self.checkBox_walkanimal.setText(_translate("MainWindow", "walkanimal"))
        self.checkBox_local.setText(_translate("MainWindow", "local"))
        self.checkBox_pal.setText(_translate("MainWindow", "pal"))
        self.pushButtonPrevious.setText(_translate("MainWindow", "prev"))
        self.pushButtonNext.setText(_translate("MainWindow", "next"))
        self.pushButtonSaveLabels.setText(_translate("MainWindow", "Save labels"))
